# Generated by Django 5.2.3 on 2025-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('summary_excel', models.FileField(blank=True, null=True, upload_to='summaries/')),
                ('bar_chart', models.ImageField(blank=True, null=True, upload_to='charts/')),
                ('pie_chart', models.ImageField(blank=True, null=True, upload_to='charts/')),
            ],
        ),
    ]
