# Generated by Django 5.2.3 on 2025-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='videoupload',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for video processing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='bar_chart',
            field=models.FileField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='pie_chart',
            field=models.FileField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
