# Generated by Django 5.2.3 on 2025-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_videoupload_options_videoupload_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='bar_chart',
            new_name='bar_chart_image',
        ),
        migrations.RenameField(
            model_name='videoupload',
            old_name='pie_chart',
            new_name='pie_chart_image',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='processed',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='detection_csv',
            field=models.FileField(blank=True, null=True, upload_to='detection_logs/'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='non_smoke_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='processed_csv',
            field=models.FileField(blank=True, null=True, upload_to='processed_csvs/'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='smoke_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='status',
            field=models.CharField(default='Uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='successful_ocr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='total_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='total_plates_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='unique_plates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
